package com.supplysync.modules.storemanager.service.impl;

import com.supplysync.modules.storemanager.dto.DashboardSummaryDTO;
import com.supplysync.repository.*;
import com.supplysync.modules.storemanager.service.DashboardService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class DashboardServiceImpl implements DashboardService {

    @Autowired private ProductRepository productRepository;
    @Autowired private InventoryRepository inventoryRepository;
    @Autowired private PurchaseOrderRepository purchaseOrderRepository;
    @Autowired private SalesRecordRepository salesRecordRepository;
    @Autowired private NotificationRepository notificationRepository;

    @Override
    public DashboardSummaryDTO getSummary() {
        DashboardSummaryDTO summary = new DashboardSummaryDTO();
        summary.setTotalProducts(productRepository.countAllActive());
        summary.setLowStockCount(inventoryRepository.countLowStockItems());
        summary.setPendingOrdersCount(purchaseOrderRepository.countPendingOrders());
        summary.setTotalInventoryItems((int) inventoryRepository.count());
        
        BigDecimal revenue = salesRecordRepository.calculateTotalRevenue();
        summary.setMonthlyRevenue(revenue != null ? revenue : BigDecimal.ZERO);

        // Fetch actual notifications
        summary.setRecentNotifications(notificationRepository.findTop10ByOrderByCreatedAtDesc().stream()
            .map(n -> new DashboardSummaryDTO.NotificationDTO(n.getTitle(), n.getMessage(), n.getType(), "Just now"))
            .collect(Collectors.toList()));

        // Mock activities (or connect to StockHistory later)
        List<DashboardSummaryDTO.RecentActivityDTO> activities = new ArrayList<>();
        activities.add(new DashboardSummaryDTO.RecentActivityDTO("Stock Update", "Stock updated for several items", "2 mins ago"));
        activities.add(new DashboardSummaryDTO.RecentActivityDTO("Report Generated", "PDF report generated by Store Manager", "10 mins ago"));
        summary.setRecentActivities(activities);

        return summary;
    }

    @Override
    public Object getSalesAnalytics() {
        return salesRecordRepository.getDailySales();
    }
}
